### ISSUE TITLE
updateState clarification?

### ISSUE THREAD

**Issue by crazy4groovy** [nyteshade/rzero-tools#2]
It not clear from the README where `this.props.updateState` comes from, and how it's functionally different than `store.setState` (other than it's sub-section of the state it's operating on).

Assuming this lib magically adds `updateState` to the props, would it be better to call it `this.props.setState` (of course not to be confused with `this.setState` .... right?)

**Comment by nyteshade** [comment]
I will call out the differences. The props updateState method is injected by the decorator and it differs from setState in that you will only be modifying the slice of the store you specified in the decorator. 

Store.setState modifies the entire store.

**Comment by nyteshade** [comment]
Let me know if that makes things a bit clearer

**Comment by crazy4groovy** [comment]
I think that's a little clearer, about the injected part. Thanks!
